version: '3.4'

services:
  postgres:
    image: postgres:14.2-alpine3.15
    container_name: 'postgre'
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: OrderDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sa1234
    ports:
      - 5432:5432


  redis:
    image: redis:6.2
    container_name: 'redis'
    ports:
      - 5002:6379

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 5003:5672
      - 5004:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq
    healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:5004"]
     interval: 30s
     timeout: 10s
     retries: 5

volumes:
  db_volume: 
  rabbitmq_data:
  rabbitmq_log: